sudo: required

services:
  - docker

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

install:
  - docker build --pull -t cristianvasquez/h-eye .
  - docker push cristianvasquez/h-eye